version: "3"

networks:
  local:
    driver: bridge

services:
  dashboard-generator:
    image: lab3agritechpaloit/bdd-req-tracer:latest
    container_name: dashboard-generator
    depends_on:
      - grafana
    env_file:
      - .env
    volumes:
      - ./CucumberTestReport.json:/app/CucumberTestReport.json
    networks:
      local:


  grafana:
    image: grafana/grafana:8.1.1
    platform: linux/amd64
    container_name: dashboard-grafana
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: db:3306
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_db_user
      GF_DATABASE_PASSWORD: password
    networks:
      local:


  db:
    image: mysql:5.7
    container_name: dashboard-db
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: grafana_db
      MYSQL_ROOT_PASSWORD: passowrd
    volumes:
      - ./db:/tmp/db
    command: mysqld --init-file="/tmp/db/init-db.sql"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      local:
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
      
